[timing]
daily_start_time = 07:30:00

[pumps.pump0]
pin_name = "P8_11"
ml_per_s = 2.9
ml_per_day = 20.0
enable = false

[pumps.pump1]
pin_name = "P8_12"
ml_per_s = 4.0
ml_per_day = 30.0
enable = false

[pumps.pump2]
pin_name = "P8_15"
ml_per_s = 4.1
ml_per_day = 30.0
enable = false

[pumps.pump3]
pin_name = "P8_16"
ml_per_s = 3.2
ml_per_day = 30.0
enable = false
